### ISSUE TITLE
Crashing on 3.0

### ISSUE THREAD

**Issue by MusouCrow** [ChemiKhazi/Sprytile#138]
Enabling the plugin through Blender Preferences leads to instant crash
Using macOS arm

**Comment by ongamex** [comment]
Same happens on Windows as well (at least for me).

Version is 0.5.20
![image](https://user-images.githubusercontent.com/6237727/150510985-9d1c7408-b371-40b4-80f0-918ab8a510e0.png)

Just go to edit mode and use use the Build or Paint tool.

**Comment by ChemiKhazi** [comment]
A new version, 0.5.25, has been released on itch that should fix issues with Blender 3.0. Please note that previous bugs have not yet been addressed, this version just ensures that it runs in 3.0
