### ISSUE TITLE
In 3D view work plane indicator

### ISSUE THREAD

**Issue by not-surt** [ChemiKhazi/Sprytile#25]
It'd be nice if there was a visual indicator in the 3D view to indicate the current work plane right where you are working.
I imagine a translucent quad placed at the 3D cursor position would be sufficient. It could be sized to match the current grid size to convey that information as well.
Would be nice to have options for always off, always on and on only during view transform.

**Comment by ChemiKhazi** [comment]
I'd love to have this too but Blender doesn't seem to have a good way to draw gizmos into the scene from add-ons, at least from what I've researched. I can draw it over the scene but I don't think that would be a good compromise.

There's supposed to be a big overhaul of Blender soon which might necessitate rewriting parts of Sprytile. If it includes the ability to draw gizmos into the scene, this would definitely be something I'll implement.

**Comment by ChemiKhazi** [comment]
Hmm, considering this again, maybe just overlaying the grid indicator over the scene might be an acceptable compromise.
