### ISSUE TITLE
Version number in zipped directory name prevents addon from working

### ISSUE THREAD

**Issue by not-surt** [ChemiKhazi/Sprytile#29]
The github releases have the scripts contained in a directory with the version number appended which, for me, prevents them working with Blender 2.78's "Install Add-on from File..".
If I rename the directory in the zip to just "Sprytile" it installs and works fine.

**Comment by ChemiKhazi** [comment]
I'm not sure I have control over how Github exports the zip files in the tagged releases. The file structure is also probably going to be used for the script updating referenced in issue #20 

Current supported upgrade method is to download again from itch.io which is packaged correctly for Blender.
