### ISSUE TITLE
Paint mode off indication

### ISSUE THREAD

**Issue by not-surt** [ChemiKhazi/Sprytile#32]
Would it be possible to add some indication for when no paint mode is active.
Either an "off" button or have all paint mode buttons toggled to off.
It's rather unintuitive to switch into edit mode and see the build button highlighted but not be in build mode.

**Comment by ChemiKhazi** [comment]
Definitely something I've thought about before. I'm working around the limitations of Blender's UI system so it may take a while to figure out a better system.
