### ISSUE TITLE
Tile transforms preview in scene view

### ISSUE THREAD

**Issue by ChemiKhazi** [ChemiKhazi/Sprytile#45]
When user transforms tiles (rotation/flip), a preview of the transform should be briefly drawn in the scene view at the mouse position.

**Comment by not-surt** [comment]
The 3D equivalent of an "on-canvas brush preview" would be a nice feature.

**Comment by ChemiKhazi** [comment]
Implemented, but possibly will cause slowdowns on larger scenes.
