### ISSUE TITLE
Selecting Paint or Build causes nearest-neighbour upscaling in the viewport as an apparent side-effect

### ISSUE THREAD

**Issue by TazeTSchnitzel** [ChemiKhazi/Sprytile#47]
When you use Sprytile's Paint or Build mode on an object in Blender's Edit mode, it changes the affected object's texture to use nearest-neighbour as a side-effect. I believe this is because when Sprytile makes the OpenGL call to change the texture's magnification filter in order to draw the tilemap, that texture is shared by the object shown in the Blender viewport.

This caused me a lot of confusion, because I didn't realise the crisp scaling I was seeing was an (accidental?) consequence of entering Sprytile's Paint/Build mode. I assumed Setup Pixel Texture had done that. So, when I restarted Blender later and reopened the same file, I couldn't figure out why it had blurry smooth texture upscaling again.

Of course, I wanted crisp nearest-neighbour texture upscaling, I just didn't realise I'd gotten it by accident. This wouldn't have affected me if I'd changed my User Preferences and disabled the “Mipmaps” option already.

I'm not sure if there's anything to do here. Possibly there might be some advantage to making an actual feature out of disabling nearest-neighbour upscaling via calling OpenGL directly, because that means you can get crisp nearest-neighbour upscaling, without sacrificing smooth downscaling with mipmaps.

**Comment by ChemiKhazi** [comment]
Thanks for the report! I'll look into this, perhaps the OpenGL state isn't being restored after drawing the GUI.

**Comment by TazeTSchnitzel** [comment]
Yeah, `draw_offscreen` calls `glTexParameteri` and changes the magnification filter to nearest-neighbour, but doesn't later change it back.

**Comment by ChemiKhazi** [comment]
If you're comfortable with fixing this, I gladly welcome pull requests :)

**Comment by TazeTSchnitzel** [comment]
Took a little research, but I did it, I think: https://github.com/ChemiKhazi/Sprytile/pull/48
