### ISSUE TITLE
Change license to GNU GPL

### ISSUE THREAD

**Issue by gaudecker** [ChemiKhazi/Sprytile#51]
Hi,

I noticed that Sprytile is currently licensed under the MIT license. Since Blender's Python API is licensed under the GNU GPL, it requires any derivative works to be licensed under the GPL as well.

See the [official FAQ](https://www.blender.org/support/faq/):

> **What about Add-ons or my Python scripts?**
> 
> If you share or publish Python scripts – if they use the Blender API calls – have to be made available compliant to the GNU GPL as well.

Thanks, I love this plugin!

**Comment by ChemiKhazi** [comment]
Thanks, was not aware of this. Since there's no fundamental incompatibilities, I'll change the license when I have the chance.

You're welcome, look forward to seeing what people make with it.

**Comment by not-surt** [comment]
> it requires any derivative works to be licensed under the GPL as well
Wrong.

> have to be made available **compliant** to the GNU GPL
Correct.

MIT is GPL compatible.

**Comment by ChemiKhazi** [comment]
Okay, did some reading on this and MIT is GPL compatible so it seems I can just leave the license alone then.
