### ISSUE TITLE
Move work plane along axis

### ISSUE THREAD

**Issue by not-surt** [ChemiKhazi/Sprytile#52]
It'd be nice if there was some way to move the work plane along its axis without having existing geometry to snap to.

Maybe modifier+mousewheel to move up and down by grid steps.

**Comment by ChemiKhazi** [comment]
This is an existing feature, I just didn't cover it in the initial tutorials. Pressing shift while snapping will toggle between vertex snap and grid snap modes.

I recently updated the [advanced tutorial to cover this](https://chemikhazi.github.io/Sprytile/advanced-features/#cursor-snap-modes) but I haven't publicized the docs update yet.

**Comment by not-surt** [comment]
I know about grid snap, but can't find any way to move the work plane with it.
How do you get it to move along the axis?

**Comment by ChemiKhazi** [comment]
If Sprytile's snap mode is set to grid, holding the `S` key should let you move the blender cursor along with the work plane using your mouse.

It works like cursor vertex snapping while holding `S`, pressing shift while in snap mode toggles between vertex and grid snapping.

**Comment by not-surt** [comment]
Yes, but that's still moving on the fixed work plane.
I want to move the work plane itself along its perpendicular axis.
So for example you can easily place ground tiles at differing elevations.

**Comment by ChemiKhazi** [comment]
Ah, got it now! That would be a useful feature.
